### PR TITLE
Added Synapse launcher to apps

### PR DESCRIPTION
**Pull request by nevillepark**

### CODE REVIEW

**Comment by monsieurh** [comment]
Quick question before merging : is synapse available in the elementary application store ?

**Comment by nevillepark** [comment]
Whoops, it is—for some reason I thought it wasn't. Are we just doing ones not available via AppCentre?

**Comment by monsieurh** [comment]
Basically, yes. The purpose isn't to replace the Appcentre, but rather to provide all the tweaks the AppCentre *misses*.

**Comment by nevillepark** [comment]
Gotcha! Will delete this plugin.

**Pull request closed without merging**
